# Generated by Django 3.1.5 on 2021-09-16 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='someone',
        ),
    ]
