# Generated by Django 3.1.5 on 2021-09-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicians', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ambition_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='focus_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='honesty_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='persuasiveness_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='respect_rate',
            field=models.IntegerField(default=0),
        ),
    ]
