# Generated by Django 3.1.5 on 2021-09-20 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('politicians', '0003_auto_20210920_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='post',
            new_name='postz',
        ),
    ]
