# Generated by Django 3.1.5 on 2021-09-21 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('politicians', '0004_auto_20210920_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='postz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='politicians.post'),
        ),
    ]
