# Generated by Django 3.1.5 on 2021-09-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicians', '0005_auto_20210921_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ambition_rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='review',
            name='focus_rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='general_rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='honesty_rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='persuasiveness_rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='respect_rate',
            field=models.IntegerField(),
        ),
    ]
