# Generated by Django 3.1.5 on 2021-09-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicians', '0006_auto_20210921_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
